version: '3.9'
services:
  postgres:
    image: postgres:16.1
    container_name: onlineshop-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: catalog
    ports:
      - "5434:5432"
    volumes:
      - onlineshop-data:/var/lib/postgresql/data

volumes:
  onlineshop-data:
