version: '3.9'
services:
  postgres:
    image: postgres:16.1
    container_name: online-store-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d
      - onlineshop-data:/var/lib/postgresql/data

  catalog:
    build: ./catalog
    container_name: online-store-catalog
    ports:
      - "8081:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres/catalog
    depends_on:
      - postgres

  user:
    build: ./user
    container_name: online-store-user
    ports:
      - "8082:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres/users
    depends_on:
      - postgres

  auth:
    build: ./auth
    container_name: online-store-auth
    ports:
      - "8083:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres/auth
    depends_on:
      - postgres

volumes:
  onlineshop-data:
