openapi: "3.0.3"
info:
  title: "online_store API"
  description: "online_store API"
  version: "1.0.0"
servers:
- url: "http://localhost:8080"
paths:
  /tokens/generate:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/GenerateTokensRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ValidationApiError"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TokensResponse"
  /tokens/refresh:
    post:
      description: ""
      requestBody:
        content:
          '*/*':
            schema:
              $ref: "#/components/schemas/RefreshTokensRequest"
        required: true
      responses:
        "400":
          description: "Bad Request"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/ValidationApiError"
        "200":
          description: "OK"
          content:
            '*/*':
              schema:
                $ref: "#/components/schemas/TokensResponse"
components:
  schemas:
    GenerateTokensRequest:
      type: "object"
      properties:
        email:
          type: "string"
        password:
          type: "string"
    ApiError:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        status:
          type: "string"
        message:
          type: "string"
      required:
      - "status"
      - "message"
    ValidationErrorItem:
      type: "object"
      properties:
        field:
          type: "string"
        message:
          type: "string"
      required:
      - "field"
      - "message"
    ValidationApiError:
      type: "object"
      properties:
        code:
          type: "integer"
          format: "int32"
        status:
          type: "string"
        message:
          type: "string"
        validationErrors:
          type: "array"
          items:
            $ref: "#/components/schemas/ValidationErrorItem"
      required:
      - "status"
      - "message"
      - "validationErrors"
    TokensResponse:
      type: "object"
      properties:
        accessToken:
          type: "string"
        accessTokenExpiration:
          type: "integer"
          format: "int64"
        refreshToken:
          type: "string"
        refreshTokenExpiration:
          type: "integer"
          format: "int64"
      required:
      - "accessToken"
      - "refreshToken"
    RefreshTokensRequest:
      type: "object"
      properties:
        refreshToken:
          type: "string"